In [27]:
# 计算a的平方加上b的三次方
import time

def pysum():  
    a = [0, 1, 2, 3, 4]
    b = [9, 8, 7, 6, 5]
    c = []
    for i in range(len(a)):
        c.append(a[i]**2 + b[i]**3)
    return c

print(pysum())



[729, 513, 347, 225, 141]


In [28]:
# 使用Numpy
import numpy as np

def npSum():
    a = np.array([0, 1, 2, 3, 4])
    b = np.array([9, 8, 7, 6, 5])
    c = a**2 + b**3
    return c

print(npSum())



[729 513 347 225 141]


In [30]:
# ndarry对象的属性
# .ndim：维度的数量
a = np.array([[0,1,2,3],
             [4,5,6,7]])
print(a.ndim)
print(a.dtype)


2
int32


In [2]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [4]:
np.zeros((3, 6), dtype=np.int32)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
x = np.ones((2,3,4))
print(x)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [9]:
x.shape

(2, 3, 4)

In [10]:
a = np.linspace(1,10,4)
print(a)

[ 1.  4.  7. 10.]


In [12]:
b = np.linspace(1, 10, 4, endpoint=False)
print(b)

[1.   3.25 5.5  7.75]
